### ISSUE TITLE
Create a go container runner

### ISSUE THREAD

**Issue by AodhAnd** [AodhAnd/bbb-xtool#2]
Based on requirements in run-container.sh, make a CLI able to run this docker image given some arguments.
## Todo
- [x] Check that the needed docker image exists
- [ ] Run docker container with a basic command
- [ ] Add source code location argument handling
- [ ] Run docker container with mounted location
- [ ] Get desired command from arguments
- [ ] Run the docker container with the specified command
- [ ] Deal with user permissions (see `entrypoint.sh`)
